# Variables

@baseURL = http://localhost:3333

# Health check
# @name healhCheck

GET {{baseURL}}/health

###

# Get rooms
# @name getRooms

GET {{baseURL}}/rooms

###

# Create room
# @name createRoom 

POST {{baseURL}}/rooms
Content-Type: application/json

{
    "name": "sala de teste",
    "description": "Essa é uma sala de teste"
}

###


@roomId = {{createRoom.response.body.$.roomId}}


###

# Get room questions
# @name getRoomQuestions
GET {{baseURL}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion 

POST {{baseURL}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "O que é Vue.js e a sua diferença em relação ao Angular?"
}